version: '2'

networks:
    monitor:
        driver: bridge

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        restart: always
        volumes:
            - /home/app/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - /home/app/prometheus/node_down.yml:/etc/prometheus/node_down.yml
        ports:
            - "9090:9090"
        networks:
            - monitor

                 
    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        restart: always
        ports:
            - "3000:3000"
        networks:
            - monitor
        depends_on:
            - prometheus


    alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        hostname: alertmanager
        restart: always
        volumes:
            - /home/app/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        ports:
            - "9093:9093"
        networks:
            - monitor
        depends_on:
            - grafana

    node-exporter:
        image: quay.io/prometheus/node-exporter
        container_name: node-exporter
        hostname: node-exporter
        restart: always
        ports:
            - "9100:9100"
        networks:
            - monitor
        depends_on:
            - alertmanager

    # cadvisor:
    #     image: google/cadvisor:v0.29.0
    #     container_name: cadvisor
    #     hostname: cadvisor
    #     restart: always
    #     volumes:
    #         - /:/rootfs:ro
    #         - /var/run:/var/run:rw
    #         - /sys:/sys:ro
    #         - /data/docker_containers/:/var/lib/docker:ro
    #     ports:
    #         - "9092:8080"
    #     networks:
    #         - monitor
    #     depends_on:
    #         - node-exporter
